workleap/ov-igloo-ui

- .storybook/styles.css
- .stylelintrc.json
- packages/Button/package.json
- packages/Button/src/button.scss
- packages/Card/package.json
- packages/Card/src/card.scss
- packages/Ellipsis/package.json
- packages/Ellipsis/src/ellipsis.scss
- packages/Kashim/package.json
- packages/Kashim/src/kashim.scss
- yarn.lock
- @igloo-ui/icons@latest
- @igloo-ui/tokens@latest
jira: OV-34270
> Update Igloo packages

- .changeset/silver-poems-worry.md
- packages/IconButton/README.md
- packages/IconButton/package.json
> docs(iconbutton): correction to readme

- .changeset/happy-buttons-judge.md
- packages/Button/src/Button.stories.tsx
- packages/Button/src/Button.tsx
Quick rename of property (change in IconButton coming next).
Bonus: Apply changes to be able to see the properties description in Storybook.
> feat: Apply changes to Button package only

- .changeset/angry-camels-appear.md
- packages/Tooltip/src/tooltip.scss
> feat: replace background color

- packages/ButtonGroup/src/ButtonGroupItem.stories.tsx
> doc: hide ButtonGroupItem from storybook

- .changeset/grumpy-stingrays-cross.md
- packages/Hyperlink/src/Hyperlink.tsx
> fix(Hyperlink): render the content of translation

- .changeset/light-yaks-dress.md
- packages/Tooltip/src/tooltip.scss
- yarn.lock
> fix(Tooltip): add new variables for negative position of arrow

- .changeset/gold-monkeys-tickle.md
- packages/Toaster/README.md
> chore(docs): fix import of toaster in doc

- .changeset/gold-crabs-complain.md
- .eslintrc.json
- packages/Toggle/src/Toggle.tsx
> fix(Toggle): fix propagation of parent onClick

- package.json
- yarn.lock
Devrait corriger:
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/47
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/46
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/45
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/44
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/43
> Mise à jour de Lerna pour corriger les alertes dependabot

- yarn.lock
Fix:
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/49
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/50
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/51
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/52
> Fix dependabot alerts #49, #50, #51 and #52

- .changeset/healthy-oranges-repair.md
- packages/Toggle/src/toggle.scss
> Fix Switch position in Toggle element

- .changeset/eighty-plums-dance.md
- packages/Input/src/Input.stories.tsx
- packages/Input/src/Input.tsx
- packages/Input/src/input.scss
> Add Suffix icon position in Input component

- .changeset/tender-days-relate.md
- package.json
- packages/Modal/README.md
- packages/Modal/package.json
- packages/Modal/src/Modal.stories.tsx
- packages/Modal/src/Modal.tsx
- packages/Modal/src/modal.scss
- yarn.lock
- Also added an onAfterClose event that is called after the animation is complete
- In order to see the animation when closing the modal, we need to remove the isOpen check surrounding <modal />
> Feat: Added animation when opening and closing a modal

- .changeset/eleven-snails-lay.md
- packages/Tooltip/src/Tooltip.stories.tsx
- packages/Tooltip/src/Tooltip.tsx
Changed the mouseleave event to use native js so it works with disabled elements as children.
> Fix: Tooltip component

- website/styles/components/_example.scss
**Modal Demo**
There is a space missing between the buttons in the footer
**Checkbox Demo**
The alignment with the checkboxes is not good
> chore: Fixing issues on demo page in the doc

- .changeset/strong-ducks-drop.md
- packages/Button/src/button.scss
> fix(Button): fix the hover state of the disabled secondary button

- .changeset/brave-apes-explain.md
- .changeset/hot-cameras-deny.md
- packages/Modal/src/modal.scss
- packages/Tooltip/src/Tooltip.stories.tsx
- packages/Tooltip/src/tooltip.scss
and properly around block elements.
> Fix: Make sure tooltips show above modals 

- netlify.toml
> chore(CI): fix error 500 when the preview is deployed on Netlify

- .changeset/poor-otters-knock.md
- packages/Dialog/src/Dialog.stories.tsx
- packages/Dialog/src/Dialog.tsx
it's a specific variant of dialog used for destructive actions
> feat(Dialog): Add danger props

- website/pages/tokens.js
- move the fonts installation on new section
- fix variable name
- remove ref of _color.css
OV-40827
> docs: update of the guide for the use of tokens.

- .changeset/kind-jokes-compete.md
- packages/Tabs/src/tabs.scss
> fix(Tabs): update the space between the label and the blue bar.

- .changeset/ten-toes-happen.md
- packages/FormGroup/README.md
in relation to the use of the `FormGroup`
#326 OV-41451
> chore(docs): fix the error of the documentation

- yarn.lock
Fix:
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/63
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/69
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/71
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/72
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/73
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/75
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/76
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/77
> Fix Dependabot alerts #63, #69, #71, #72, #73, #75, #76 and #77

- .changeset/khaki-cups-build.md
- packages/AreaChart/src/AreaChart.tsx
Displays in the x-axis + tooltip the utc date instead of the local date
OV-41871
> fix(AreaChart): Fix issues with x-axis render

- .changeset/clever-taxis-nail.md
- packages/Textarea/src/Textarea.tsx
https://user-images.githubusercontent.com/2379339/227002101-feb4d291-976c-4093-8e12-e2429489de9b.mp4
OV-42459
> fix: display the number that was negative when adding an emoji

- .changeset/thirty-dots-carry.md
- packages/Datepicker/src/Datepicker.stories.tsx
- packages/Datepicker/src/Datepicker.tsx
- packages/Datepicker/src/components/Calendar.tsx
- packages/Datepicker/src/datepicker.scss
> feat: add new options for disabled date and new callback for clear date

- .changeset/five-tigers-own.md
- packages/Datepicker/src/datepicker.scss
> fix: cursor display on hover of an inactive date

- .changeset/heavy-zoos-lick.md
- packages/TextEditor/src/plugins/OnFocusPlugin.tsx
> Fix: Linting for textEditor

- utils/generate-api.mjs
- website/components/ReferenceLinks.js
- website/pages/component/index.js
- website/pages/index.js
- website/styles/components/_example.scss
- website/styles/components/_mdx-content.scss
- website/styles/components/_toc.scss
> chore(doc): Fix the size of table of content

- .changeset/selfish-bugs-unite.md
- packages/Button/src/Button.stories.tsx
- packages/Button/src/Button.tsx
- packages/Button/src/button.scss
> Add props for reset the size to the default on mobile

- .changeset/eight-ravens-roll.md
- .storybook/useBrand.js
- packages/Toggle/package.json
- packages/Toggle/src/Toggle.tsx
- packages/Toggle/src/toggle.scss
Rebranded the toggle to follow Hopper Brand.
> rebrand of the toggle

- .changeset/shiny-numbers-tan.md
- packages/Datepicker/src/Datepicker.tsx
> Fix: Error with minDate value that is greater than maxDate

- .storybook/styles.css
As we are moving toward a base 16 rem scale, it was necessary to convert all storybook css rules to the new scale when in a Workleap theme.
> converted base 10 to 16 in storybook css file

- .changeset/few-dragons-sit.md
- .storybook/useBrand.js
- packages/ProgressBar/package.json
- packages/ProgressBar/src/ProgressBar.stories.tsx
- packages/ProgressBar/src/ProgressBar.tsx
- packages/ProgressBar/src/progress-bar.scss
> Rebrand ProgressBar

- .changeset/light-jobs-think.md
- .storybook/useBrand.js
- packages/Stepper/package.json
- packages/Stepper/src/step.scss
- packages/Stepper/src/stepper.scss
Rebrand of Stepper component.
Task IGL-66
> Rebrand of Stepper

- .changeset/eighty-pots-complain.md
- packages/Datepicker/src/datepicker.scss
> Fix(Datepicker): Changes cursor to not-allowed when input is disabled

- .changeset/tasty-suits-grab.md
- packages/Modal/src/modal.scss
Fix for https://github.com/gsoft-inc/ov-igloo-ui/issues/568
> moved the close button closer to the modal edges

- .changeset/good-owls-rhyme.md
- packages/List/src/list-item.scss
Issue : https://github.com/gsoft-inc/ov-igloo-ui/issues/596
Adjusted compact list item height to 2.5rem.
> compact list should follow the small option size

- .changeset/big-pumas-hang.md
- .changeset/three-kangaroos-protect.md
- packages/Combobox/src/Combobox.tsx
- packages/Combobox/src/combobox-input.scss
- packages/Input/src/input.scss
- packages/List/src/list-item.scss
- packages/Select/src/select.scss
- packages/TagPicker/src/tag-picker-result.scss
- packages/TagPicker/src/tag-picker.scss
- packages/Textarea/src/textarea.scss
> Issue 589 590 595 fix

- .changeset/good-coats-eat.md
- packages/Tag/src/tag.scss
> fix(tag): added space between icon and border

- .changeset/tame-kids-hear.md
- packages/ButtonGroup/src/ButtonGroup.stories.tsx
- packages/ButtonGroup/src/ButtonGroup.tsx
- packages/ButtonGroup/src/button-group.scss
add a data tag to the first and last elements to style borders radius
> Fix component rendering when used with a tooltip

- .changeset/unlucky-deers-listen.md
- packages/Breadcrumb/src/Breadcrumb.tsx
- packages/Carousel/src/Carousel.tsx
- packages/Hyperlink/src/Hyperlink.tsx
- packages/Modal/src/Modal.tsx
- shared/components/src/visual-identifier/VisualIdentifier.tsx
- Some components were not passing down the class to cloned elements.
> Fix issue where classNames were not passed to children when cloned

- .changeset/new-pans-raise.md
- packages/Metric/src/metric.scss
- packages/Metric/src/score.scss
Updated the fluctuate variant for the Metric component
- Text color is now on par with the design.
- Margin between the value and pt(s) is now accurate.
> Metric Component Fluctuate text color update. 

- .changeset/green-turkeys-end.md
- packages/Filter/src/filter.scss
- Changed the border color when Filter is disabled.
> Fix of filter border color when disabled

- .changeset/rare-coats-push.md
- packages/Dialog/package.json
updated Dialog dependency on Modal
> updated Dialog dependency on Modal

- .changeset/khaki-grapes-drop.md
- packages/Tabs/src/Tabs.tsx
> Propagate extra props to the Tabs component wrapper.

- .changeset/spicy-tables-call.md
- packages/Button/src/button.scss
Updated the Ghost button colors for the Workleap brand.
> Updated the ghost button colors

- .changeset/flat-monkeys-argue.md
Bumped version of all components having a dependency on Button and IconButton
> version bump

- .changeset/breezy-dodos-bow.md
- packages/Modal/src/modal.scss
When in mobile buttons should be at the bottom per design discussions. This PR aims at fixing this.
> fix for 729 - buttons should be at the bottom when in a Modal

- .changeset/bright-starfishes-greet.md
- .changeset/tricky-pigs-applaud.md
- packages/Tag/jest.config.js
- packages/Tag/src/Tag.stories.tsx
- packages/Tag/src/Tag.tsx
- packages/Tag/src/__snapshots__/Tag.test.tsx.snap
- packages/Tag/src/tag.scss
Tag
- Compensated centering of text in Tags using ABC Favorit Mono
- Added Inactive apperance to Tag
> Centered default and primary text - added inactive appearance in Tag

- package.json
- packages/AreaChart/src/AreaChart.stories.tsx
- yarn.lock
The problem is not with the component but with the nFormater function, which is in example. To keep track, we added an example that displays negative values and modified the function.
> Add a negative value display example

- .changeset/tough-bobcats-invite.md
- packages/Pager/src/Pager.tsx
- packages/Pager/src/__snapshots__/Pager.test.tsx.snap
Fix for https://github.com/gsoft-inc/ov-igloo-ui/issues/793
> workleap brand pager chevron size fix

- .changeset/heavy-cats-hang.md
- packages/Dialog/package.json
Dialog needed an update dependency on Modal.
> dialog dependency on modal update

- .changeset/small-bananas-check.md
- packages/Dialog/src/dialog.scss
Fix for alignment in title and sub title in Dialog component.
Fix for subtitle color for Dialog component.
> dialog title/subtitle alignment and color update

- .changeset/lucky-bulldogs-heal.md
- packages/Disclosure/src/disclosure.scss
Updated Disclosure to match the intended look in Hopper.
> updated Disclosure UI in workleap theme

- .changeset/cool-icons-share.md
- packages/Filter/src/filter.scss
Hover state of a selected filter had a dark gray border color this fixes this issue.
> updated the UI of selected filter hover state

- .changeset/metal-icons-own.md
- packages/Button/src/button.scss
When disabled a button still had a pressed effect if pressed.
Button Active/Selected colors were not applied in Workleap theme
> Fixed disabled press state appearance / fixed active state in workleap theme for button

- .changeset/fast-actors-add.md
- packages/Alert/src/alert.scss
A misunderstanding rendered the Alert UI fix not as intended.
> fixed padding issue in Alert horizontal mode

- .changeset/nine-avocados-listen.md
- packages/Dialog/package.json
- yarn.lock
updated dialog to latest hopper tokens (v 4)
> updated dialog to latest hopper tokens

- .changeset/funny-beans-dress.md
- packages/Button/src/button.scss
Updated the button secondary text color to match Hopper design.
> [ds-269] Updated button secondary ghost look to match hopper

- .changeset/cyan-zoos-crash.md
- packages/Alert/src/Alert.tsx
Allow AlertButton to have a loading state
> EP-5748: Add loading prop to AlertButton

- .changeset/stupid-crabs-shop.md
Need to bump these to fix the CSS of components using the broken ones
> Add a patch changeset for components that use list/tabs
