.changeset/stale-parrots-admire.md, packages/IconButton/package.json, packages/IconButton/src/IconButton.stories.tsx, packages/IconButton/src/IconButton.tsx
refactor: Change IconButtonProps interface extends
fix: Storybook `IconButton` now use rounded property instead of theme
refactor: Update minimal `@igloo-ui/button` version to 0.1.6
=> `IconButtonProps` interface extends change in `@igloo-ui/icon-button`

.changeset/fresh-balloons-attack.md, packages/Button/src/Button.tsx
=> Fix Button having object other than string in title

.changeset/forty-apricots-battle.md, packages/IconButton/src/icon-button.scss
This property is useless since it is already defined in .ids-btn--ghost. Also, the variable does not exist.
=> Fix(iconbutton): Remove useless background property already specified in button

.changeset/poor-donkeys-brake.md, packages/Button/src/button.scss
=> fix: secondary button empty bg on hover state

package.json, yarn.lock
Update version of `@netlify/plugin-nextjs` used to fix dependabot alerts for `node-forge`
Fix:
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/36
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/37
- https://github.com/gsoft-inc/ov-igloo-ui/security/dependabot/38
=> Update dependencies to fix dependabot alert on node-forge

.changeset/red-badgers-sip.md, packages/Button/src/button.scss
Dans portal le style associé a la class `.ids-btn` override le style de `.ids-btn--ghost-danger` dans un context particulier. En attendant de trouver pour quel raison cette erreur apparait on prefix la class avec `.ids-btn`
=> fix(Button): Temporary quick fix on ghost danger button

.changeset/famous-humans-cough.md, packages/AreaChart/src/AreaChart.stories.tsx, packages/AreaChart/src/AreaChart.tsx, packages/AreaChart/src/area-chart.scss, packages/AreaChart/src/hooks/useDynamicYAxisWidth.tsx
- rename the css animation to avoid conflicts
- update y-axis size when the loading state disappeared 
- change the orientation of animation for empty state
Issue #298, OV-41029
=> fix(AreaChart): Issues with loading and empty state

.changeset/silly-windows-cover.md, packages/Dialog/README.md, packages/Modal/README.md
We explain how to work around the problem of the output on the modal and the dialog component
OV-42443
=> docs: Adding a troubleshooting section in the doc

.changeset/young-snakes-own.md, packages/Modal/src/Modal.tsx, packages/Modal/src/modal.scss
The CSS `transform` instruction used to center the modal make a position offset when using drag&drop with `react-beautiful-dnd` inside a modal.
- Wrapping the modal in a div with `className="ids-modal-wrapper"`
- Remove transform and fixed positioning on the modal
- Center the modal inside the wrapper by using flex instruction in the wrapper
```diff
+ Test Suites: 41 passed, 41 total
+ Tests:       257 passed, 257 total
+ Snapshots:   59 passed, 59 total
```
=> Center modal using flex instructions

.changeset/twelve-balloons-think.md, packages/TextEditor/src/TextEditor.stories.tsx, packages/TextEditor/src/plugins/OnFocusPlugin.tsx
The effect adding the onBlur to the text editor was missing the cleanup. This means that onBlur would be called multiple times, sometime with stale data because of closures.
Also added a story to test this. (the pre commit hook also decide to autofix some styling)
=> Fix: Add cleanup for onBlur

.changeset/heavy-queens-kneel.md, packages/TextEditor/src/TextEditor.tsx, packages/TextEditor/src/plugins/FloatingLinkEditorPlugin.tsx
We would like to open link in a new tab but the target attribute was never set.
- Adding a toggle IconButton to set `true`/`false` the `target='[_blank|_self]'` attribute of the link from the link editor
| Internal link | External link |
| --- | --- |
| ![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/9695045/82e856bb-4a07-4f2d-9a88-76b91bbc6e23) | ![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/9695045/8cb4b677-0558-434b-a468-62b9d2361742) |
```json
{"root":{"children":[{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Internal link","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"link","version":1,"rel":"noreferrer","target":"_self","title":null,"url":"https://www.google.com/"},{"detail":0,"format":0,"mode":" …
```
=> Add possibility to open link in a new tab

.changeset/moody-moose-serve.md, packages/TextEditor/src/plugins/ToolbarPlugin.tsx
Adding a tabindex when the `showOnFocus` option is active solves the problem.
Story: IGL-81 
Issue: GH-529
=> Fix: the toolbar to remain in focus in safari

.changeset/giant-points-itch.md, packages/TextEditor/src/plugins/FloatingLinkEditorPlugin.tsx, packages/TextEditor/src/plugins/floating-link-editor.scss
We would like to fix the overflow url when editing a link.
- Manage the overflow and add a tooltip
```diff
+ Test Suites: 45 passed, 45 total
+ Tests:       293 passed, 293 total
+ Snapshots:   63 passed, 63 total
```
=> #530 Fix url too long in link editor plugin

.changeset/fresh-poems-tickle.md, packages/Select/src/select-value.scss, yarn.lock
=> Restores alignment between icon and text in a compact select

.changeset/silver-ghosts-bake.md, packages/Radio/src/radio.scss
The hover is not displayed correctly in Igloo 
**OV**
Selected:
Selected hover:
**Rebrand**
Selected:
Selected hover:
---
Selected hover:
IGL-99
=> Hover display for a selected radio

.changeset/chilly-doors-breathe.md, packages/Combobox/src/combobox.scss, packages/Select/src/select.scss
Fix for issue #593 : Select & Combobox - Make sure the focus state is the same as Orbiter's focus state
=> Select & Combobox - Make sure the focus state is the same as Orbiter's focus state

.changeset/sour-files-chew.md, packages/Modal/src/modal.scss
Close icon in desktop view was centered, this was problematic when a Modal title was two line or more high.
=> fixed close icon position in modal

.changeset/hot-fishes-divide.md, packages/Textarea/src/textarea.scss
- Textarea font family was not applied due to a wrongly typed variable name, this has been fixed.
=> fixed wrong variable reference in textarea

.changeset/little-pandas-drive.md, packages/Alert/src/alert.scss, packages/Select/src/select-input.scss, packages/Select/src/select-value.scss
- Inline Alert border-radius was set at 0, where it should have been 8px.
- Icons in a "closed" Select were not the right colour.
=> UI adjustment to Alert and Select

.changeset/green-queens-fix.md, packages/Pager/rollup.config.js, rollup.config.js
- added the igloo provider as an external package in the rollup config. This ensures that the provider's code is not duplicated in each package. Before this change, the useLocale hook was not returning the expected value passed to the provider
=> Fix to the pager's localization

.changeset/silly-bees-fix.md, packages/Radio/src/radio.scss
Small radio label did not used the right variable resulting in a wrong font size, this has been fixed.
=> fix for small radio label text not being the right size

.changeset/smooth-cobras-work.md, packages/Popover/src/popover.scss
- Removed padding on title when no close button is present.
- Removed padding on content.
- Adjusted close button position in Workleap theme.
=> Removed unnecessary padding on popover title and content

.changeset/khaki-penguins-design.md, packages/StackedBar/src/StackedBar.stories.tsx, packages/StackedBar/src/StackedBar.tsx
Fix for issue #716.
The way the code was working is that it was checking for the first item in the dataSet even if it's value was 0, items with a 0 value are not rendered, resulting in situations where we had items with no border radius even though they were the first item rendered. The same applies to the lastItem.
=> fix for border radius in the StackedBar component

.changeset/silver-apes-impress.md, packages/Button/src/button.scss
Fix issue #767.
- Gap is now used in button, this will ensure that any icon wether coming from Hopper or elsewhere will have the right spacing.
=> Transitionned to gap in button

.storybook/preview-head.html, packages/Avatar/README.md, packages/Avatar/src/Avatar.stories.tsx, packages/Datepicker/src/Datepicker.stories.tsx, packages/List/src/List.stories.tsx, packages/Select/src/Select.stories.tsx
- Now preloading fonts (tentative fix on Area Charts tests that we're failling)
- Avatar now use an url that is the same instead of changing on every http get
- List Members now use an url that is the same instead of changing on every http get
- DatePicker tests was using today, which is not great. But turns out all the other tests where turned off, so this one being turned on was a mistake
=> Update chromatic stories that were failing a lot

.changeset/khaki-glasses-crash.md, packages/Metric/src/Metric.tsx, packages/Metric/src/Score.tsx
Fix for issue : https://github.com/gsoft-inc/ov-igloo-ui/issues/787
=> usage of hopper icon in metric score

.changeset/empty-lies-clap.md, packages/AreaChart/src/AreaChart.tsx, packages/AreaChart/src/ChartTooltip.tsx, packages/AreaChart/src/area-chart.scss, packages/AreaChart/src/chart-tooltip.scss, packages/VerticalBarChart/src/VerticalBarChart.tsx, packages/VerticalBarChart/src/vertical-bar-chart.scss
AreaChart Graph line was too complex to use and always be accurate color wise. This PR aims at reverting to a solid line color until more tests and questions are answered.
=> AreaChart Graph gradient line to solid line

.changeset/famous-ants-shout.md, .changeset/loud-dancers-jump.md, packages/Combobox/src/Combobox.tsx, packages/Combobox/src/ComboboxInput.tsx, packages/Combobox/src/combobox.scss, packages/Input/src/input.scss, packages/TagPicker/src/tag-picker.scss, packages/TextEditor/src/text-editor.scss, packages/Textarea/src/textarea.scss
Input / Combobox and Textarea are now using border color as focus style.
=> fixed ui with inputs color in workleap theme

.changeset/blue-ghosts-applaud.md, packages/Alert/src/alert.scss
Horizontal Callout in Workleap theme should have a font-weight of 410, this PR fixes it.
=> fix callout horizontal font weight

.changeset/tidy-experts-pretend.md, packages/Breadcrumb/src/breadcrumb.scss
Breadcrumb were not wrapping when in a tight space.
=> Fixed an issue where breadcrumbs were not wrapping in mobile

packages/Alert/src/Alert.tsx, packages/Alert/src/alert.scss
- Padding is now smaller when in Workleap theme.
- Button is not ghost in horizontal appearance anymore in Workleap theme.
- In mobile, the items stack instead of being horizontal.
=> Fix Alert UI to match Hopper style

.changeset/giant-rules-vanish.md, packages/ActionMenu/src/ActionMenu.test.tsx, packages/ActionMenu/src/ActionMenu.tsx, packages/Alert/src/Alert.tsx, packages/Button/src/Button.tsx, packages/Combobox/src/Combobox.stories.tsx, packages/Combobox/src/Combobox.test.tsx, packages/Combobox/src/Combobox.tsx, packages/Filter/src/Filter.tsx, packages/IconButton/src/IconButton.test.tsx, packages/IconButton/src/IconButton.tsx, packages/List/src/List.tsx, packages/List/src/ListItem.tsx, packages/Select/src/Select.tsx, packages/Stepper/src/Stepper.test.tsx, packages/Stepper/src/Stepper.tsx, packages/Toaster/src/Toaster.stories.tsx, packages/Toaster/src/Toaster.tsx
- Added the possibility to use a reactNode in Toaster message.
- Added the possibility to use a reactNode in ListItem label.
`onClick` typings have been extended from `void` to `MouseEventHandler<HTMLButtonElement`.
- ActionMenuOption
- Button
- IconButton
- Filter
- Stepper
=> Updated typings

.changeset/loud-cameras-invent.md, packages/AreaChart/src/AreaChart.tsx
We've seen an issue where a client had a range from Nov 1 to Nov 30, but the graph showed "Dec. 30" instead. The endRange property seems to work fine, so it's most likely a display issue. Looking at the formatSpecialMonth method, there was a usage of the wrong variable, which i think was the issue. 
This is a tentative fix that we will ship to the client to see if everything works as expected
=> Fixed an issue where the wrong month label was shown in rare cases

.changeset/little-crabs-provide.md, packages/Select/src/Select.tsx
Reeopened this PR under my name to fix the chromatic issue:
https://github.com/gsoft-inc/ov-igloo-ui/pull/856
=> [EP-3941]: Add prop to Select to disable portalling

.changeset/tidy-suits-wave.md, packages/Dropdown/package.json, packages/Dropdown/src/Dropdown.tsx, packages/Dropdown/src/__snapshots__/Dropdown.test.tsx.snap, packages/Popover/package.json, packages/Popover/src/Popover.tsx, packages/Popover/src/__snapshots__/Popover.test.tsx.snap, packages/TextEditor/package.json, packages/TextEditor/src/plugins/FloatingLinkEditorPlugin.tsx, packages/Tooltip/package.json, packages/Tooltip/src/Tooltip.test.tsx, packages/Tooltip/src/Tooltip.tsx, packages/Tooltip/src/__snapshots__/Tooltip.test.tsx.snap, yarn.lock
- Update floating-ui package to latest
- Render FloatingPortals only when they are mounted [per docs](https://floating-ui.com/docs/FloatingPortal#:~:text=Note,not%20in%20use.)
[DS-540](https://workleap.atlassian.net/browse/DS-540)
[EP-3989](https://workleap.atlassian.net/browse/EP-3989)
In OV, we have run into an issue where floating portals occasionally do not open. This was thought to be isolated to one component in OV so a workaround was https://github.com/gsoft-inc/ov-igloo-ui/pull/856. This worked for the once case but now that the bug has been seen elsewhere, we would like to fix it for all floating portals to prevent the issue popping back up elsewhere. I believe the latest updates to floating-ui include fixes for the portal IDs that may fix the issue, so updating these packages …
=> Fix dropdown floating portals

.changeset/old-weeks-pump.md
The provider has not changed so it does not need a bump, and is affecting other package's versions in the changeset PR
=> Remove provider version bump

.changeset/itchy-frogs-push.md, packages/List/src/list.scss, packages/Tabs/src/tabs.scss
The List and Tabs both redeclare the CSS Layers for some reason, although this is already done in globals.scss. For whatever reason the redundant declaration was resulting in the build CSS for List including the layer tag at the end with no semicolon. This produced no issues for the List itself, but when the Select used that CSS block the missing semicolon broke the CSS following it:
Resulting in broken select items:
Removing the redundant @layer fixes the built CSS
=> EP-6633: Fix broken css caused by redundant layer declarations
